apiVersion: v1
kind: Service
metadata:
  name: fayol-backend
  labels:
    app: fayol-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3333
    targetPort: 3333
    protocol: TCP
    name: http
  selector:
    app: fayol-backend
