apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - redis.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: fayol
  app.kubernetes.io/component: infrastructure
