apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/name: fayol-python-ai
  app.kubernetes.io/component: ai
  app.kubernetes.io/part-of: fayol
