apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fayol

bases:
  - ../../base

replicas:
  - name: backend
    count: 3
  - name: web-app
    count: 2
  - name: telegram-bot
    count: 2

commonLabels:
  environment: production
  app.kubernetes.io/version: v1.0.0

patchesStrategicMerge:
  - patch-backend.yaml
  - patch-web-app.yaml
  - patch-python-ai.yaml

configMapGenerator:
  - name: fayol-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - NODE_ENV=production

secretGenerator:
  - name: fayol-secrets
    behavior: merge
    envs:
      - secrets.env
