apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - infrastructure/
  - backend/
  - web-app/
  - python-ai/
  - bi-reports/

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: fayol

namespace: fayol
