apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fayol-dev

bases:
  - ../../base

commonLabels:
  environment: dev

# Configurações específicas de dev
configMapGenerator:
  - name: fayol-config
    behavior: merge
    literals:
      - log-level=debug
      - rate-limit-max=1000

images:
  - name: fayol/backend
    newTag: dev
  - name: fayol/web-app
    newTag: dev
  - name: fayol/python-ai
    newTag: dev
  - name: fayol/bi-reports
    newTag: dev
