apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fayol-staging

bases:
  - ../../base

commonLabels:
  environment: staging

# Configurações específicas de staging
configMapGenerator:
  - name: fayol-config
    behavior: merge
    literals:
      - log-level=info
      - rate-limit-max=100

images:
  - name: fayol/backend
    newTag: staging
  - name: fayol/web-app
    newTag: staging
  - name: fayol/python-ai
    newTag: staging
  - name: fayol/bi-reports
    newTag: staging
