apiVersion: v1
kind: ConfigMap
metadata:
  name: fayol-config
  namespace: fayol
data:
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  ENVIRONMENT: "production"
  # Adicione aqui outras configs públicas se necessário